### ISSUE TITLE
Issue when helmetsblocksun=true

### ISSUE THREAD

**Issue by kaimokene** [actioninja/BurningSun#6]
Hello it seems theres an issue with the mod if you set it to true it doesnt only make so u dont burn in sunlight while wearing a helmet but also without a helmet.
Version 1.11.2-2.0.0.21
Forge version 13.20.0.2310

**Comment by actioninja** [comment]
I forgot that the way itemstacks work in 1.11 changed.

Previously, if a slot for an item was empty, it was null.  In 1.11+, an empty itemstack contains a stack of size 0 with a type of air.  You have to use a helper function to check if it's empty instead of just seeing if it's null.

So since the helmet checking code just checked if the head slot was null, it now is never null and so you now will never burn if that config option is enabled.

I've already made a fix for it, just need to push it.
